### ISSUE TITLE
transfer action failed

### ISSUE THREAD

**Issue by FishMeat** [iotexproject/iotex-docs#12]
I run a docker instance according to https://docs.iotex.io/docs/open-testnet,  and  the container is up.
I use wallet create two addresses, and sent some iotexs to one, but it is failed.
![image](https://user-images.githubusercontent.com/7263252/49682399-5e890a80-faee-11e8-9f54-8b1f3419244b.png)
![image](https://user-images.githubusercontent.com/7263252/49682402-75c7f800-faee-11e8-8222-9cdfe8e0f2ee.png)
my node config:
``` 
# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodeType: "full_node"            # should be one of "delegate", "full_node", and "lightweight"

network:
  # replace with your external IP address
  host: "118.31.35.57"
  port: 30555
  bootstrapNodes:
  - "bootnode.iotexconnect.io:30555"
  ttl: 2

chain:
  chainDBPath: "./chain.db"
  trieDBPath: "./trie.db"
  producerPrivKey: "925f0c9e4b6f6d92f2961d01aff6204c44d73c0b9d0da188582932d4fcad0d8ee8c66600"
  producerPubKey: "336eb60a5741f585a8e81de64e071327a3b96c15af4af5723598a07b6121e8e813bbd0056ba71ae29c0d64252e913f60afaeb11059908b81ff27cbfa327fd371d35f5ec0cbc01705"
  enableFallbackToFreshDb: true
  enableSubChainStartInGenesis: false

consensus:
  scheme: "NOOP"
  blockCreationInterval: 2s

blockSync:
  interval: 1s

system:
  httpProfilingPort: 6060
  httpMetricsPort: 8080

explorer:
  enabled: true
```
